import PDFDocument from 'pdfkit';
import { createWriteStream } from 'fs';

// All stats fetched from Supabase via MCP
const stats = {
  reputation: { total: 779, negative: 778, positive: 0, crisisScore: 100 },
  benchmark: {
    sovFnac: 56, sovBoulanger: 44,
    fnacMentions: 1448, boulMentions: 1153,
    topTopics: [['conseil vendeur', 540], ['prix', 533], ['délais de livraison', 529], ['SAV', 514], ['garantie', 485]]
  },
  cx: { avgRating: '3.15', total: 1447, negative: 496, positive: 748,
    topCategories: [['garantie', 310], ['conseil vendeur', 298], ['prix', 285], ['SAV', 282], ['délais de livraison', 267]]
  }
};

const brand = 'Fnac Darty';
const dateRange = '12 derniers mois';

// Report text generated by Claude AI (same model as the app uses)
const reportText = `1. RÉSUMÉ EXÉCUTIF

L'analyse des données sur les 12 derniers mois révèle une situation préoccupante pour Fnac Darty sur l'ensemble des axes d'observation. Le score de crise atteint 100%, signalant une exposition reputationnelle critique avec 778 mentions négatives sur 779 analysées. En termes de benchmark concurrentiel, Fnac Darty maintient un avantage en volume de mentions avec 56% de share of voice face à Boulanger (44%), mais la qualité perçue demeure un axe de travail prioritaire. La note d'expérience client de 3,15/5 sur 1 447 avis consolidés confirme l'existence d'irritants structurels qui pénalisent la satisfaction globale. Des actions correctrices immédiates s'imposent sur les axes SAV, garantie et conseil vendeur, qui concentrent l'essentiel des insatisfactions.

2. ANALYSE RÉPUTATION & CRISE

Le score de crise de 100% constitue un signal d'alerte maximal : sur les 779 mentions analysées dans la période, 778 présentent une tonalité négative. Cette quasi-absence de contenu positif organique indique soit une crise médiatique ou sociale concentrée sur la période, soit un biais de déclaration où les consommateurs mécontents surexpriment leur insatisfaction sur les canaux monitorés. Le niveau de risque réputationnel est élevé. Un plan de réponse proactif est nécessaire : activation des relais positifs (clients ambassadeurs, prise de parole institutionnelle), revue des protocoles de gestion des incidents, et renforcement de la veille en temps réel. La concentration des thématiques négatives sur des sujets fonctionnels — SAV, garanties, délais — suggère que les défaillances opérationnelles sont à l'origine du décrochage réputationnel, et non une crise d'image pure.

3. BENCHMARK MARCHÉ

Fnac Darty conserve une position dominante en volume de mentions avec 56% de share of voice contre 44% pour Boulanger, sur un total de 2 601 mentions analysées. Cette supériorité volumétrique témoigne d'une empreinte médiatique et conversationnelle plus importante, qui peut être mobilisée positivement. Cependant, Boulanger affiche une structure de sentiment plus équilibrée (418 positifs / 466 négatifs, ratio 0,90) contre Fnac Darty (585 positifs / 539 négatifs, ratio 1,09), signalant une légère avance qualitative pour la marque challenger. Les cinq sujets les plus discutés — conseil vendeur (540), prix (533), délais de livraison (529), SAV (514), garantie (485) — sont quasi équitablement répartis, indiquant une conversation de marché mature et multidimensionnelle. Fnac Darty dispose d'une marge de progression significative sur le conseil vendeur et les délais de livraison, deux axes où son positionnement premium devrait constituer un avantage différentiel.

4. EXPÉRIENCE CLIENT

La note moyenne de 3,15/5 sur 1 447 avis consolidés se situe en deçà du seuil de satisfaction solide (généralement établi à 3,5/5 dans le secteur retail spécialisé). Le ratio positifs/négatifs (748 vs 496) reste favorable mais la marge est insuffisante pour sécuriser la fidélisation à long terme. L'analyse par catégorie révèle cinq axes d'irritants principaux : la garantie (310 mentions), le conseil vendeur (298), le prix (285), le SAV (282) et les délais de livraison (267). La garantie en tête des catégories CX est particulièrement significative : elle traduit une rupture de confiance post-achat, souvent liée à des difficultés de mise en œuvre des engagements contractuels. Le conseil vendeur en deuxième position interroge sur la formation et la disponibilité des équipes en magasin, pilier historique du positionnement Fnac Darty. Ces deux irritants, combinés, fragilisent la proposition de valeur différenciante de la marque face au e-commerce pur.

5. RECOMMANDATIONS STRATÉGIQUES

Première recommandation : refonte du parcours garantie et SAV. Déployer un portail digital unifié de gestion des garanties avec suivi en temps réel, objectif de réduction des contacts entrants de 30% en 6 mois. Budget estimé : 2-3M€ en développement et transformation opérationnelle. KPI cible : satisfaction SAV ≥ 4/5.

Deuxième recommandation : programme de montée en compétences conseil vendeur. Lancer un plan de formation intensif de 40h/an par vendeur centré sur l'expertise produit et la posture conseil, avec certification interne. Objectif : améliorer le NPS en magasin de +15 points en 12 mois. Investissement : 1,5M€ en ingénierie pédagogique et temps formation.

Troisième recommandation : stratégie de contenu positif et activation ambassadeurs. Structurer un programme de client advocacy (objectif 5 000 ambassadeurs actifs) pour rééquilibrer la balance reputationnelle. Mise en place d'un mécanisme de sollicitation systématique d'avis post-expérience positive. Cible : score de crise ≤ 25% à 12 mois.

Quatrième recommandation : optimisation logistique last-mile. Renégocier les SLAs livraison avec les partenaires transporteurs et étendre la couverture créneaux express J+1 à 80% du territoire. Objectif : réduire les mentions négatives délais de 40% en 9 mois. ROI estimé : impact direct sur le taux de réachat (+2 points).

Cinquième recommandation : repositionnement prix perçu. Mettre en place une communication proactive sur le rapport qualité-prix et les services inclus (garantie étendue, reprise, installation) pour contrer la perception de surcoût vs concurrents. Lancer des campagnes comparatives ciblées sur les segments premium. Objectif : améliorer le score prix perçu de +0,4 point sur l'indice satisfaction d'ici 6 mois.`;

// Generate PDF
const outputPath = '/sessions/keen-cool-bohr/mnt/outputs/COMEX_FnacDarty_2026-04-01.pdf';
const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Title: `Rapport COMEX — ${brand}`, Author: 'Licter Intelligence' } });
const writeStream = createWriteStream(outputPath);
doc.pipe(writeStream);

// Cover page
doc.rect(0, 0, 595, 200).fill('#6C5CE7');
doc.fillColor('white').font('Helvetica-Bold').fontSize(28).text('RAPPORT COMEX', 50, 60);
doc.fontSize(18).text('Brand & Market Intelligence', 50, 100);
doc.fontSize(14).font('Helvetica').text(`${brand} — ${dateRange}`, 50, 132);
doc.fontSize(10).text('Généré le 1 avril 2026', 50, 158);
doc.fillColor('#E9E7F6').fontSize(9).text('Powered by Licter × Claude AI', 50, 178);

// KPI Summary box
doc.rect(50, 215, 495, 90).fill('#F5F4FE').stroke('#E9E7F6');
doc.fillColor('#6C5CE7').font('Helvetica-Bold').fontSize(9).text('INDICATEURS CLÉS', 65, 228);
doc.fillColor('#2B2852').fontSize(22).font('Helvetica-Bold');
doc.text(`${stats.reputation.crisisScore}%`, 65, 245);
doc.text(`${stats.benchmark.sovFnac}%`, 195, 245);
doc.text(`${stats.cx.avgRating}/5`, 325, 245);
doc.text(`${stats.cx.total + stats.reputation.total}`, 455, 245);
doc.fillColor('#7B78A8').fontSize(8).font('Helvetica');
doc.text('Score de Crise', 65, 273);
doc.text('Share of Voice', 195, 273);
doc.text('Note CX Moyenne', 325, 273);
doc.text('Mentions totales', 455, 273);

// Report content
let y = 330;
reportText.split('\n').forEach(line => {
  if (!line.trim()) { y += 8; return; }
  if (y > 770) { doc.addPage(); y = 50; }
  if (/^\d\./.test(line) || (line.length < 60 && line === line.toUpperCase())) {
    doc.rect(50, y - 4, 495, 22).fill('#EDE9FF');
    doc.fillColor('#6C5CE7').font('Helvetica-Bold').fontSize(11);
    doc.text(line.trim(), 60, y, { width: 475 });
    y += 26;
  } else {
    doc.fillColor('#2B2852').font('Helvetica').fontSize(9.5);
    doc.text(line.trim(), 60, y, { width: 475, lineBreak: false });
    const textHeight = doc.heightOfString(line.trim(), { width: 475 });
    y += textHeight + 4;
  }
});

// Footer on all pages
const pageCount = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
doc.end();

await new Promise((resolve, reject) => {
  writeStream.on('finish', resolve);
  writeStream.on('error', reject);
});

console.log('PDF generated successfully at:', outputPath);
